//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger_Food_Distribution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequest()
        {
            this.CollectionActivities = new HashSet<CollectionActivity>();
            this.DistributionActivities = new HashSet<DistributionActivity>();
        }
    
        public int CollectRequestId { get; set; }
        public int RestaurantId { get; set; }
        public string FoodDescription { get; set; }
        public string ApproximateQuantity { get; set; }
        public System.DateTime PreservationTime { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<int> AssignedEmployeeId { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionActivity> CollectionActivities { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionActivity> DistributionActivities { get; set; }
    }
}
